### ISSUE TITLE
Gunicorn doesn't work

### ISSUE THREAD

**Issue by colettecello** [colettecello/dcon-vagrant-test#1]
run from /var/dcon  gunicorn main:app throws this:
http://pastebin.com/HCWQZxGG

**Comment by sneak** [comment]
gunicorn is not finding the python module in the app. check gunicorn docs for how to specify its PYTHONPATH (the list of directories it searches for modules) or just try setting PYTHONPATH in the gunicorn init script to include the directory that holds dcon

**Comment by colettecello** [comment]
Specified -pythonpath as /var/dcon newrem:app (and as /var/dcon/newrem just for funsies) and got this guy:
http://pastebin.com/Yks4LWhs

**Comment by sneak** [comment]
it needs a double dash, e.g.:

    --pythonpath /var/dcon

Also, can you show me the full gunicorn command that's being run, either by you or grepped out of

    ps auxwwww | grep gunicorn

**Comment by colettecello** [comment]
fixed in c66c3
