### ISSUE TITLE
more than one user can't write to db simultaneously

### ISSUE THREAD

**Issue by colettecello** [colettecello/dcon-vagrant-test#2]

**Comment by colettecello** [comment]
mysql is now installed

**Comment by sneak** [comment]
Is the app using a MySQL db?

-- 
Jeffrey Paul   +1 (312) 361-0355
5539 AD00 DE4C 42F3 AFE1 1575 0524 43F4 DF2A 55C2

**Comment by colettecello** [comment]
It sure is. (See dcon.yaml)

**Comment by colettecello** [comment]
it's also configured with a dcon user for the db.
